name: CD Workflow

on:
  push:
    branches:
      - master

jobs:
  my-job-cd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install
        run: yarn

      - name: Build
        run: yarn Build

      - name: Deploy
        run: yarn deploy
